/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Liveness probe — returns 200 when the process is running.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login
         * @description Authenticate user with username and password, setting HttpOnly session cookie.
         */
        post: operations["login_api_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout
         * @description Invalidate current session and remove the session cookie.
         */
        post: operations["logout_api_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Me
         * @description Return profile of the currently authenticated user.
         */
        get: operations["get_me_api_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Users
         * @description List all user accounts (Admin only).
         */
        get: operations["list_users_api_admin_users_get"];
        put?: never;
        /**
         * Create User
         * @description Create a new user account (Admin only).
         */
        post: operations["create_user_api_admin_users_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/seasons": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Seasons
         * @description List all card seasons/classes.
         */
        get: operations["list_seasons_api_seasons_get"];
        put?: never;
        /**
         * Create Season
         * @description Create a new season class (Admin only).
         */
        post: operations["create_season_api_seasons_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/player-seasons": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Player Seasons
         * @description Search and paginate player season cards with filters.
         *
         *     Supports unaccented Vietnamese search, exact position, or position groups (FW, MF, DF, GK).
         */
        get: operations["list_player_seasons_api_player_seasons_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/player-seasons/{card_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Player Season
         * @description Get player season card detail by UUID.
         */
        get: operations["get_player_season_api_player_seasons__card_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/player-seasons/{card_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update Player Salary
         * @description Update salary of a card (Admin only; rejected with POOL_LOCKED if draft active).
         */
        patch: operations["update_player_salary_api_admin_player_seasons__card_id__patch"];
        trace?: never;
    };
    "/api/admin/players/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Import Players Csv
         * @description Import cards from CSV upload (Admin only; rejected with POOL_LOCKED if draft active).
         */
        post: operations["import_players_csv_api_admin_players_import_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tournaments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Tournaments
         * @description List all tournaments (newest first).
         */
        get: operations["list_tournaments_api_tournaments_get"];
        put?: never;
        /**
         * Create Tournament
         * @description Create a new tournament with validated TournamentRules (ADMIN only).
         */
        post: operations["create_tournament_api_tournaments_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tournaments/{tournament_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Tournament
         * @description Get tournament details with teams.
         */
        get: operations["get_tournament_api_tournaments__tournament_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tournaments/{tournament_id}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Complete Tournament
         * @description Manually mark a tournament as COMPLETED (ADMIN only).
         */
        post: operations["complete_tournament_api_tournaments__tournament_id__complete_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tournaments/{tournament_id}/teams": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Teams
         * @description List teams in a tournament ordered by draft_order.
         */
        get: operations["list_teams_api_tournaments__tournament_id__teams_get"];
        put?: never;
        /**
         * Add Team
         * @description Add a team to a tournament (ADMIN only).
         *
         *     If adding this team makes the count >= 2, tournament transitions DRAFT → READY.
         */
        post: operations["add_team_api_tournaments__tournament_id__teams_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/teams/{team_id}/roster": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Team Roster
         * @description Return the team's drafted roster populated from draft_picks table.
         */
        get: operations["get_team_roster_api_teams__team_id__roster_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tournaments/{tournament_id}/draft/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start Draft
         * @description Start a new draft session for a READY tournament (ADMIN only).
         */
        post: operations["start_draft_api_tournaments__tournament_id__draft_start_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tournaments/{tournament_id}/draft": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Tournament Draft
         * @description Get the latest/active draft session details for a tournament.
         */
        get: operations["get_tournament_draft_api_tournaments__tournament_id__draft_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/drafts/{draft_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Draft Detail
         * @description Get full draft details, current timer, and team status.
         */
        get: operations["get_draft_detail_api_drafts__draft_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/drafts/{draft_id}/picks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Draft Picks
         * @description Get all picks in the draft session formatted for the draft board.
         */
        get: operations["list_draft_picks_api_drafts__draft_id__picks_get"];
        put?: never;
        /**
         * Make Pick
         * @description Submit a single player card pick for the current team's turn.
         */
        post: operations["make_pick_api_drafts__draft_id__picks_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/drafts/{draft_id}/pause": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Pause Draft
         * @description Pause an active draft session (ADMIN only).
         */
        post: operations["pause_draft_api_drafts__draft_id__pause_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/drafts/{draft_id}/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Resume Draft
         * @description Resume a paused draft session (ADMIN only).
         */
        post: operations["resume_draft_api_drafts__draft_id__resume_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/drafts/{draft_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cancel Draft
         * @description Cancel an active draft session (ADMIN only).
         */
        post: operations["cancel_draft_api_drafts__draft_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tournaments/{tournament_id}/matches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Tournament Matches
         * @description List all scheduled and played matches for a tournament.
         */
        get: operations["list_tournament_matches_api_tournaments__tournament_id__matches_get"];
        put?: never;
        /**
         * Create Match
         * @description Schedule a match between two teams in a tournament (ADMIN only).
         */
        post: operations["create_match_api_tournaments__tournament_id__matches_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/matches/{match_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Match Detail
         * @description Get match details with SIMULTANEOUS ban secrecy applied (BR-M04).
         */
        get: operations["get_match_detail_api_matches__match_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/matches/{match_id}/bans/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start Ban Phase
         * @description Start Tactical Ban Phase for a SCHEDULED match (ADMIN only).
         */
        post: operations["start_ban_phase_api_matches__match_id__bans_start_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/matches/{match_id}/bans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Submit Ban
         * @description Submit a single player card ban for the authenticated team.
         */
        post: operations["submit_ban_api_matches__match_id__bans_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/matches/{match_id}/bans/{ban_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Ban
         * @description Delete a pending ban before confirmation.
         */
        delete: operations["delete_ban_api_matches__match_id__bans__ban_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/matches/{match_id}/bans/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Confirm Bans
         * @description Confirm bans for the authenticated team.
         */
        post: operations["confirm_bans_api_matches__match_id__bans_confirm_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/matches/{match_id}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Complete Match
         * @description Mark match as COMPLETED (ADMIN only).
         */
        post: operations["complete_match_api_matches__match_id__complete_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** BanItemResponse */
        BanItemResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Banningteamid
             * Format: uuid
             */
            banningTeamId: string;
            /**
             * Targetteamid
             * Format: uuid
             */
            targetTeamId: string;
            /**
             * Playerseasonid
             * Format: uuid
             */
            playerSeasonId: string;
            /** Playername */
            playerName: string;
            /** Position */
            position: string;
            /**
             * Rating
             * @default 0
             */
            rating: number;
            /** Seasoncode */
            seasonCode: string;
            /** Seasonbadgeurl */
            seasonBadgeUrl?: string | null;
            /** Createdat */
            createdAt: string;
        };
        /** Body_import_players_csv_api_admin_players_import_post */
        Body_import_players_csv_api_admin_players_import_post: {
            /** File */
            file: string;
        };
        /** CreateMatchRequest */
        CreateMatchRequest: {
            /**
             * Hometeamid
             * Format: uuid
             */
            homeTeamId: string;
            /**
             * Awayteamid
             * Format: uuid
             */
            awayTeamId: string;
            /** Scheduledat */
            scheduledAt?: string | null;
        };
        /** CreateSeasonRequest */
        CreateSeasonRequest: {
            /** Code */
            code: string;
            /** Name */
            name: string;
            /** Badgeurl */
            badgeUrl?: string | null;
            /** Year */
            year?: number | null;
            /**
             * Game
             * @default FC Online
             */
            game: string;
        };
        /** CreateTeamRequest */
        CreateTeamRequest: {
            /** Name */
            name: string;
            /** Draftorder */
            draftOrder: number;
        };
        /** CreateTournamentRequest */
        CreateTournamentRequest: {
            /** Name */
            name: string;
            rules?: components["schemas"]["TournamentRulesSchema"];
        };
        /** CreateUserRequest */
        CreateUserRequest: {
            /** Username */
            username: string;
            /** Password */
            password: string;
            /** Teamid */
            teamId?: string | null;
            /**
             * Role
             * @default TEAM_USER
             */
            role: string;
        };
        /** DraftDetailResponse */
        DraftDetailResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Tournamentid
             * Format: uuid
             */
            tournamentId: string;
            /** Status */
            status: string;
            /** Currentround */
            currentRound: number;
            /** Currentturn */
            currentTurn: number;
            /** Currentteamid */
            currentTeamId?: string | null;
            /** Turnstartedat */
            turnStartedAt?: string | null;
            /** Turnexpiresat */
            turnExpiresAt?: string | null;
            /** Remainingmillis */
            remainingMillis?: number | null;
            /** Version */
            version: number;
            /** Servertime */
            serverTime: string;
            /** Rulessnapshot */
            rulesSnapshot: {
                [key: string]: unknown;
            };
            /** Teams */
            teams: components["schemas"]["TeamDraftStatus"][];
        };
        /** DraftPickBoardItem */
        DraftPickBoardItem: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Round */
            round: number;
            /** Turnnumber */
            turnNumber: number;
            /** Salaryatpick */
            salaryAtPick: number;
            /** Pickedat */
            pickedAt: string;
            team: components["schemas"]["PickTeamDetail"];
            player: components["schemas"]["PickPlayerDetail"];
        };
        /** DraftPickRequest */
        DraftPickRequest: {
            /**
             * Playerseasonid
             * Format: uuid
             */
            playerSeasonId: string;
            /** Expectedversion */
            expectedVersion: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * ImportReport
         * @description Execution summary returned by the importer pipeline.
         */
        ImportReport: {
            /**
             * Rowsread
             * @default 0
             */
            rowsRead: number;
            /**
             * Rowsinserted
             * @default 0
             */
            rowsInserted: number;
            /**
             * Rowsupdated
             * @default 0
             */
            rowsUpdated: number;
            /**
             * Rowsskipped
             * @default 0
             */
            rowsSkipped: number;
            /** Errors */
            errors?: string[];
        };
        /** LoginRequest */
        LoginRequest: {
            /** Username */
            username: string;
            /** Password */
            password: string;
        };
        /** MakePickResponse */
        MakePickResponse: {
            pick: components["schemas"]["PickResponseItem"];
            nextState: components["schemas"]["NextStateInfo"];
        };
        /** MatchDetailResponse */
        MatchDetailResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Tournamentid
             * Format: uuid
             */
            tournamentId: string;
            /** Status */
            status: string;
            /** Scheduledat */
            scheduledAt?: string | null;
            /** Banstartedat */
            banStartedAt?: string | null;
            /** Banexpiresat */
            banExpiresAt?: string | null;
            /** Version */
            version: number;
            /** Servertime */
            serverTime: string;
            /** Rulessnapshot */
            rulesSnapshot: {
                [key: string]: unknown;
            };
            homeTeam: components["schemas"]["app__match__api__TeamSummary"];
            awayTeam: components["schemas"]["app__match__api__TeamSummary"];
            /**
             * Bans
             * @default []
             */
            bans: components["schemas"]["BanItemResponse"][];
        };
        /** NextStateInfo */
        NextStateInfo: {
            /** Currentround */
            currentRound: number;
            /** Currentturn */
            currentTurn: number;
            /** Currentteamid */
            currentTeamId?: string | null;
            /** Turnexpiresat */
            turnExpiresAt?: string | null;
            /** Status */
            status: string;
            /** Version */
            version: number;
        };
        /** PickPlayerDetail */
        PickPlayerDetail: {
            /**
             * Playerseasonid
             * Format: uuid
             */
            playerSeasonId: string;
            /**
             * Playerid
             * Format: uuid
             */
            playerId: string;
            /** Name */
            name: string;
            /** Position */
            position: string;
            /** Rating */
            rating?: number | null;
            /** Salary */
            salary: number;
            /** Imageurl */
            imageUrl?: string | null;
            season: components["schemas"]["SeasonSummary"];
        };
        /** PickResponseItem */
        PickResponseItem: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Round */
            round: number;
            /** Turnnumber */
            turnNumber: number;
            /**
             * Teamid
             * Format: uuid
             */
            teamId: string;
            /**
             * Playerseasonid
             * Format: uuid
             */
            playerSeasonId: string;
            /**
             * Playerid
             * Format: uuid
             */
            playerId: string;
            /** Salaryatpick */
            salaryAtPick: number;
            /** Pickedat */
            pickedAt: string;
        };
        /** PickTeamDetail */
        PickTeamDetail: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Draftorder */
            draftOrder: number;
        };
        /** PlayerEmbedded */
        PlayerEmbedded: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Externalplayerid */
            externalPlayerId: string;
        };
        /** PlayerSeasonListResponse */
        PlayerSeasonListResponse: {
            /** Items */
            items: components["schemas"]["PlayerSeasonResponse"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Pagesize */
            pageSize: number;
            /** Totalpages */
            totalPages: number;
        };
        /** PlayerSeasonResponse */
        PlayerSeasonResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Playerid
             * Format: uuid
             */
            playerId: string;
            /**
             * Seasonid
             * Format: uuid
             */
            seasonId: string;
            /** Position */
            position: string;
            /** Rating */
            rating?: number | null;
            /** Salary */
            salary: number;
            /** Imageurl */
            imageUrl?: string | null;
            /** Status */
            status: string;
            player: components["schemas"]["PlayerEmbedded"];
            season: components["schemas"]["SeasonEmbedded"];
        };
        /** RosterItem */
        RosterItem: {
            /**
             * Pickid
             * Format: uuid
             */
            pickId: string;
            /** Round */
            round: number;
            /** Turnnumber */
            turnNumber: number;
            /** Salaryatpick */
            salaryAtPick: number;
            /** Pickedat */
            pickedAt: string;
            player: components["schemas"]["RosterItemPlayer"];
        };
        /** RosterItemPlayer */
        RosterItemPlayer: {
            /**
             * Playerseasonid
             * Format: uuid
             */
            playerSeasonId: string;
            /**
             * Playerid
             * Format: uuid
             */
            playerId: string;
            /** Name */
            name: string;
            /** Position */
            position: string;
            /** Rating */
            rating?: number | null;
            /** Salary */
            salary: number;
            season: components["schemas"]["RosterSeasonSummary"];
        };
        /**
         * RosterResponse
         * @description Team roster populated from draft_picks table.
         */
        RosterResponse: {
            /**
             * Teamid
             * Format: uuid
             */
            teamId: string;
            /** Teamname */
            teamName: string;
            /**
             * Rostercount
             * @default 0
             */
            rosterCount: number;
            /** Budgetused */
            budgetUsed: number;
            /** Roster */
            roster?: components["schemas"]["RosterItem"][];
        };
        /** RosterSeasonSummary */
        RosterSeasonSummary: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Code */
            code: string;
            /** Name */
            name: string;
            /** Badgeurl */
            badgeUrl?: string | null;
        };
        /** SeasonEmbedded */
        SeasonEmbedded: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Code */
            code: string;
            /** Badgeurl */
            badgeUrl?: string | null;
        };
        /** SeasonResponse */
        SeasonResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Code */
            code: string;
            /** Name */
            name: string;
            /** Badgeurl */
            badgeUrl?: string | null;
            /** Game */
            game: string;
            /** Year */
            year?: number | null;
        };
        /** SeasonSummary */
        SeasonSummary: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Code */
            code: string;
            /** Name */
            name: string;
            /** Badgeurl */
            badgeUrl?: string | null;
        };
        /** StartDraftResponse */
        StartDraftResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Tournamentid
             * Format: uuid
             */
            tournamentId: string;
            /** Status */
            status: string;
            /** Currentround */
            currentRound: number;
            /** Currentturn */
            currentTurn: number;
            /** Currentteamid */
            currentTeamId?: string | null;
            /** Turnstartedat */
            turnStartedAt?: string | null;
            /** Turnexpiresat */
            turnExpiresAt?: string | null;
            /** Remainingmillis */
            remainingMillis?: number | null;
            /** Rulessnapshot */
            rulesSnapshot: {
                [key: string]: unknown;
            };
            /** Version */
            version: number;
        };
        /** SubmitBanRequest */
        SubmitBanRequest: {
            /**
             * Playerseasonid
             * Format: uuid
             */
            playerSeasonId: string;
            /** Targetteamid */
            targetTeamId?: string | null;
        };
        /** TeamDraftStatus */
        TeamDraftStatus: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Draftorder */
            draftOrder: number;
            /** Budgetused */
            budgetUsed: number;
            /** Budgetremaining */
            budgetRemaining: number;
            /** Pickedcount */
            pickedCount: number;
        };
        /** TeamResponse */
        TeamResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Tournamentid
             * Format: uuid
             */
            tournamentId: string;
            /** Name */
            name: string;
            /** Draftorder */
            draftOrder: number;
            /** Budgetused */
            budgetUsed: number;
            /** Status */
            status: string;
        };
        /** TournamentListItem */
        TournamentListItem: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Status */
            status: string;
            rules?: components["schemas"]["TournamentRulesSchema"] | null;
            /** Teamcount */
            teamCount: number;
            /** Createdat */
            createdAt: string;
        };
        /** TournamentResponse */
        TournamentResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Status */
            status: string;
            rules: components["schemas"]["TournamentRulesSchema"];
            /** Teams */
            teams: components["schemas"]["app__tournament__api__TeamSummary"][];
            /** Createdat */
            createdAt: string;
            /** Updatedat */
            updatedAt: string;
        };
        /**
         * TournamentRulesSchema
         * @description API-facing rules schema. Accepts camelCase or snake_case input, outputs camelCase.
         */
        TournamentRulesSchema: {
            /**
             * Rulesversion
             * @default 1
             */
            rulesVersion: number;
            /**
             * Rostersize
             * @default 24
             */
            rosterSize: number;
            /**
             * Budget
             * @default 305
             */
            budget: number;
            /**
             * Picktimeseconds
             * @default 30
             */
            pickTimeSeconds: number;
            /**
             * Uniqueby
             * @default PLAYER
             * @enum {string}
             */
            uniqueBy: "PLAYER" | "CARD";
            /**
             * Timeoutpolicy
             * @default AUTO_PICK_CHEAPEST
             * @enum {string}
             */
            timeoutPolicy: "SKIP_TURN" | "AUTO_PICK_CHEAPEST";
            /** Allowedseasonids */
            allowedSeasonIds?: string[];
            /**
             * Bancount
             * @default 5
             */
            banCount: number;
            /**
             * Bantimeseconds
             * @default 60
             */
            banTimeSeconds: number;
            /**
             * Bantarget
             * @default OPPONENT_ROSTER
             * @enum {string}
             */
            banTarget: "OPPONENT_ROSTER" | "OWN_ROSTER";
            /**
             * Banorder
             * @default SIMULTANEOUS
             * @enum {string}
             */
            banOrder: "SIMULTANEOUS" | "ALTERNATING";
        };
        /** UpdateSalaryRequest */
        UpdateSalaryRequest: {
            /** Salary */
            salary: number;
        };
        /** UserResponse */
        UserResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Username */
            username: string;
            /** Role */
            role: string;
            /** Teamid */
            teamId?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** TeamSummary */
        app__match__api__TeamSummary: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /**
             * Confirmed
             * @default false
             */
            confirmed: boolean;
            /**
             * Bancount
             * @default 0
             */
            banCount: number;
        };
        /** TeamSummary */
        app__tournament__api__TeamSummary: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Draftorder */
            draftOrder: number;
            /** Budgetused */
            budgetUsed: number;
            /** Status */
            status: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    login_api_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    get_me_api_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
        };
    };
    list_users_api_admin_users_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"][];
                };
            };
        };
    };
    create_user_api_admin_users_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateUserRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_seasons_api_seasons_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeasonResponse"][];
                };
            };
        };
    };
    create_season_api_seasons_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSeasonRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeasonResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_player_seasons_api_player_seasons_get: {
        parameters: {
            query?: {
                seasonId?: string | null;
                position?: string | null;
                group?: string | null;
                search?: string | null;
                page?: number;
                pageSize?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlayerSeasonListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_player_season_api_player_seasons__card_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                card_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlayerSeasonResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_player_salary_api_admin_player_seasons__card_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                card_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateSalaryRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlayerSeasonResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    import_players_csv_api_admin_players_import_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_import_players_csv_api_admin_players_import_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportReport"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_tournaments_api_tournaments_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TournamentListItem"][];
                };
            };
        };
    };
    create_tournament_api_tournaments_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTournamentRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TournamentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_tournament_api_tournaments__tournament_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tournament_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TournamentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    complete_tournament_api_tournaments__tournament_id__complete_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tournament_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TournamentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_teams_api_tournaments__tournament_id__teams_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tournament_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_team_api_tournaments__tournament_id__teams_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tournament_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTeamRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_team_roster_api_teams__team_id__roster_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                team_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RosterResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_draft_api_tournaments__tournament_id__draft_start_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tournament_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DraftDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_tournament_draft_api_tournaments__tournament_id__draft_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tournament_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DraftDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_draft_detail_api_drafts__draft_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                draft_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DraftDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_draft_picks_api_drafts__draft_id__picks_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                draft_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DraftPickBoardItem"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    make_pick_api_drafts__draft_id__picks_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                draft_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DraftPickRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MakePickResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    pause_draft_api_drafts__draft_id__pause_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                draft_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StartDraftResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resume_draft_api_drafts__draft_id__resume_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                draft_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StartDraftResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_draft_api_drafts__draft_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                draft_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StartDraftResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_tournament_matches_api_tournaments__tournament_id__matches_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tournament_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatchDetailResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_match_api_tournaments__tournament_id__matches_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tournament_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateMatchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatchDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_match_detail_api_matches__match_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                match_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatchDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_ban_phase_api_matches__match_id__bans_start_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                match_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatchDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_ban_api_matches__match_id__bans_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                match_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubmitBanRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BanItemResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_ban_api_matches__match_id__bans__ban_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                match_id: string;
                ban_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    confirm_bans_api_matches__match_id__bans_confirm_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                match_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatchDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    complete_match_api_matches__match_id__complete_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                match_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatchDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
