"""SQLAlchemy domain models for Season, Player, and PlayerSeason."""

import uuid
from datetime import datetime

from sqlalchemy import (
    CheckConstraint,
    DateTime,
    ForeignKey,
    Integer,
    String,
    UniqueConstraint,
)
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.db import Base


class Season(Base):
    """A card season/class in FC Online (e.g. 23UCL, ICON, CAP)."""

    __tablename__ = "seasons"

    id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    code: Mapped[str] = mapped_column(String(50), nullable=False)
    name: Mapped[str] = mapped_column(String(200), nullable=False)
    badge_url: Mapped[str | None] = mapped_column(String(500), nullable=True)
    game: Mapped[str] = mapped_column(String(100), nullable=False, default="FC Online")
    year: Mapped[int | None] = mapped_column(Integer, nullable=True)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)

    # Relationships
    player_seasons: Mapped[list["PlayerSeason"]] = relationship(
        "PlayerSeason", back_populates="season"
    )

    __table_args__ = (UniqueConstraint("code", name="uq_seasons_code"),)


class Player(Base):
    """Master footballer identity — one record per real player, eternal."""

    __tablename__ = "players"

    id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    name: Mapped[str] = mapped_column(String(200), nullable=False)
    # REQUIRED for deduplication; rows without this are skipped during import
    external_player_id: Mapped[str] = mapped_column(String(100), nullable=False)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)

    # Relationships
    player_seasons: Mapped[list["PlayerSeason"]] = relationship(
        "PlayerSeason", back_populates="player"
    )

    __table_args__ = (
        UniqueConstraint("external_player_id", name="uq_players_external_player_id"),
        # GIN index for unaccent+trigram player name search
        # The actual index uses immutable_unaccent() function created in migration 0001.
        # Defined explicitly in Alembic migration — not autogenerated here.
    )


class PlayerSeason(Base):
    """Card data for a player in a specific season. This is what gets drafted."""

    __tablename__ = "player_seasons"

    id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    player_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("players.id", ondelete="CASCADE"),
        nullable=False,
    )
    season_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("seasons.id", ondelete="CASCADE"),
        nullable=False,
    )
    # Original position string: ST, CF, LW, RW, CAM, CM, CDM, LM, RM, CB, LB, RB, LWB, RWB, GK
    # No collapsing; UI groups into filter chips (FW/MF/DF/GK)
    position: Mapped[str] = mapped_column(String(10), nullable=False)
    rating: Mapped[int | None] = mapped_column(Integer, nullable=True)
    # Salary must be >= 1 (enforced by DB CHECK and Pydantic)
    salary: Mapped[int] = mapped_column(Integer, nullable=False)
    image_url: Mapped[str | None] = mapped_column(String(500), nullable=True)
    status: Mapped[str] = mapped_column(String(20), nullable=False, default="ACTIVE")
    # FC stats (nullable — not all imported cards will have full stats)
    pace: Mapped[int | None] = mapped_column(Integer, nullable=True)
    shooting: Mapped[int | None] = mapped_column(Integer, nullable=True)
    passing: Mapped[int | None] = mapped_column(Integer, nullable=True)
    dribbling: Mapped[int | None] = mapped_column(Integer, nullable=True)
    defending: Mapped[int | None] = mapped_column(Integer, nullable=True)
    physical: Mapped[int | None] = mapped_column(Integer, nullable=True)

    # Relationships
    player: Mapped["Player"] = relationship("Player", back_populates="player_seasons")
    season: Mapped["Season"] = relationship("Season", back_populates="player_seasons")

    __table_args__ = (
        UniqueConstraint("player_id", "season_id", name="uq_player_seasons_player_id_season_id"),
        CheckConstraint("salary >= 1", name="ck_player_seasons_salary_positive"),
        CheckConstraint(
            "status IN ('ACTIVE', 'INACTIVE')",
            name="ck_player_seasons_status",
        ),
    )
